gText_Birch_Welcome:: @ 82C897B
	.string "Hello INMATE.\p"
	.string "Welcome to the world of SHADES...\p"
	.string "My name is VIRGIL.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “SHADE.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "beasts known as SHADES.\p"
	.string "Many years ago we suffered a CATACLYSM\n"
	.string "gave rise to these monsters.\l"
	.string "The CATACLYSM caused a mass extinction\l"
  .string "event that wiped out many species of \p"
	.string "POKéMON and destroyed their habitats.\n"
	.string "Today, we are slowly rebuilding \l"
	.string "but we have a long way to go.\p"
	.string "I’ve been undertaking research,\n"
	.string "to explore this new world and see if we\l"
  .string "can recover what we have lost.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right...\n"
	.string "What’s your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it’s {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Alright, everything is in order now.\p"
	.string "{PLAYER}{KUN}, you are being released\n"
	.string "from MAROWAK PRISON into my custody.\l"
	.string "You will be relocated to my hometown\p"
	.string "of LITTLEROOT, where i will supervise\l"
	.string "your rehabilitation.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of SHADES where horror,\l"
	.string "adventure, and desolation await.\p"
	.string "Well, I’ll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
